version: '3.1'

services:
  db:
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: dogs
      MYSQL_ROOT_PASSWORD: supersecretrootpassword
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - 33306:3306
